apiVersion : apps/v1
kind: Deployment
metadata:
  name: userrepo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userrepo
  template:
    metadata:
      labels:
        app: userrepo 
    spec:
      containers:
        - name: userrepo 
          image: ajayregis.azurecr.io/userrepo
          ports:
          - containerPort: 8082