apiVersion : apps/v1
kind: Deployment
metadata:
  name: revhire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revhire
  template:
    metadata:
      labels:
        app: revhire
    spec:
      containers:
        - name: revhire
          image: ajayregis.azurecr.io/userrevhire
          env:
          - name : DB_URL
            valueFrom: 
              secretKeyRef:
                name: db-credentials
                key: DB_URL
          - name : DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key : DB_USERNAME
          - name : DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PORT
          
